### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by stevetoro** [leslied2018/prj-rev-bwfs-dasmoto#6]
https://github.com/leslied2018/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Art%20Store/resources/css/style.css#L23-L81

There's way too much repetition here. Use more general selectors so that you can consolidate shared styles in one location and keep your CSS tidy and maintainable.

If you'd used `div` tags with the same class and `h2` tags with different IDs, you could write the following:

```css
.product h2 {
  font-size: 32px;
  font-weight: bold;
  color: white;
}

#brushes {
  background-color: mediumspringgreen;
}
```

You shouldn't be using !important for every single style. That kinda defeats the purpose of having a style that should be given priority if all styles held to that same level of priority.
